### ISSUE TITLE
Login and Signup form lack show password feature

### ISSUE THREAD

**Issue by dipak-01** [dipak-01/AnimeFlix#2]
![image](https://github.com/user-attachments/assets/b68c574b-afa0-4ede-9ec1-7098172a9286)
Add the show password feature in both of the form mentioned above

**Comment by codebymv** [comment]
I'll try and implement this today

**Comment by codebymv** [comment]
just sent a PR, I haven't worked with codebase like this before so let me know if anything needs to be adjusted!
