### ISSUE TITLE
Add a GitHub link to the footer.

### ISSUE THREAD

**Issue by dipak-01** [dipak-01/AnimeFlix#3]
![image](https://github.com/user-attachments/assets/67e0ba08-57d6-4cd0-a9ff-d29cf9994d31)
Please add the GitHub link to the GitHub repository in the footer and also use Font Awesome icons.
The reference is shown above.

**Comment by Mk281005** [comment]
@dipak-01 I want to contribute to the issue and there is a request to add hacktoberfest label to it

**Comment by dipak-01** [comment]
Apologies for the delayed response. Please start addressing the issue and remember to pull changes before committing.

**Comment by dipak-01** [comment]
Closes #6
